name: build_and_deploy

on:
  schedule:
    - cron: '23 0 * * 6' 
  push:
    branches: [
      master,
      dev
    ]

jobs:
  build_apache_images:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        moodle_version: [311,400,401,402,403]
        php_version: ['7.4','8.0','8.1','8.2','8.3']
        exclude:
          - moodle_version: 311
            php_version: '8.1'
          - moodle_version: 311
            php_version: '8.2'
          - moodle_version: 311
            php_version: '8.3'
          - moodle_version: 400
            php_version: '8.1'
          - moodle_version: 400
            php_version: '8.3'
          - moodle_version: 401
            php_version: '8.2'
          - moodle_version: 401
            php_version: '8.3'
          - moodle_version: 402
            php_version: '7.4'
          - moodle_version: 402
            php_version: '8.2'
          - moodle_version: 403
            php_version: '8.3'
          - moodle_version: 403
            php_version: '7.4'
          - moodle_version: 40
    env:
      VERSION: ${{ matrix.moodle_version }}
      PHP_VERSION: "${{ matrix.php_version }}"
    steps:
      - name: Check Out Repo 
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        if: github.ref != 'refs/heads/dev'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name : Build Docker Images
        shell: bash
        run: |
          docker --version
          ls -l ./.github
          chmod +x ".github/build_docker.sh"
          .github/build_docker.sh 'dockerfiles/apache/Dockerfile'